urls.py
from django.conf.urls import url

from . import views

app_name = 'blog'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^category/(?P<slug>[0-9a-zA-Z/-]+)/$', views.view_category, name='view_category'),
    url(r'^(?P<slug>[0-9a-zA-Z/-]+)/$', views.view_post, name='view_post'),
]

models.py
from django.db import models


class Post(models.Model):
    title = models.CharField(max_length=255, unique=True)
    slug = models.SlugField(max_length=255, unique=True)
    body = models.TextField()
    date_published = models.DateTimeField('date published', db_index=True)
    category = models.ForeignKey('blog.Category')

    def __str__(self):
        return self.title


class Category(models.Model):
    title = models.CharField(max_length=255, db_index=True)
    slug = models.SlugField(max_length=255, db_index=True)

    class Meta:
        verbose_name_plural = "categories"

    def __str__(self):
        return self.title

views.py
from blog.models import Post, Category
from django.shortcuts import render, get_object_or_404
from django.utils import timezone


def index(request):
    return render(request, 'blog/index.html', {
        'categories': Category.objects.all().order_by('title'),
        'posts': Post.objects.filter(date_published__lte=timezone.now()).order_by('-date_published')[:5]
    })


def view_post(request, slug):
    return render(request, 'blog/post.html', {
        'post': get_object_or_404(Post, slug=slug)
    })


def view_category(request, slug):
    category = get_object_or_404(Category, slug=slug)
    return render(request, 'blog/category.html', {
        'category': category,
        'posts': Post.objects.filter(category=category, date_published__lte=timezone.now())
                             .order_by('-date_published')[:5]
    })

templates/blog/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block head_title %}My Blog{% endblock %}</title>
</head>
<body>
    <h1>{% block title %}{% endblock %}</h1>
    {% block content %}
    {% endblock %}
</body>
</html>

templates/blog/category.html
{% extends 'blog/base.html' %}
{% block head_title %}{{ category.title }}{% endblock %}
{% block title %}{{ category.title }}{% endblock %}

{% block content %}
    {% if posts %}
        <ul>
        {% for post in posts %}
            <li><a href="{% url 'blog:view_post' post.slug %}">{{ post.title }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>There are no posts in this category.</p>
    {% endif %}
{% endblock %}

templates/blog/index.html
{% extends 'blog/base.html' %}
{% block title %}My Blog{% endblock %}

{% block content %}
    <h2>Categories</h2>
    {% if categories %}
        <ul>
        {% for category in categories %}
            <li><a href="{% url 'blog:view_category' category.slug %}">{{ category.title }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>There are no categories.</p>
    {% endif %}

    <h2>Posts</h2>
    {% if posts %}
        <ul>
        {% for post in posts %}
            <li><a href="{% url 'blog:view_post' post.slug %}">{{ post.title }}</a></li>
        {% endfor %}
        </ul>
    {% else %}
        <p>There are no posts.</p>
    {% endif %}

{% endblock %}

templates/blog/post.html
{% extends 'blog/base.html' %}
{% block head_title %}{{ post.title }}{% endblock %}
{% block title %}{{ post.title }}{% endblock %}

{% block content %}
    <i>{{ post.date_published }}</i>
    <br /><br />
    {{ post.body }}
{% endblock %}